### ISSUE TITLE
wp verify-checksums?

### ISSUE THREAD

**Issue by DavidGoodwin** [pwaring/sympl-scripts#1]
Perhaps the wp-cli update script should run wp-cli verify-checksums first, and warn/error or something if there is a tampered local file?

(Just a random thought)

**Comment by pwaring** [comment]
Thanks, I wasn't aware of that command. It seems to emit a lot of "File should not exist" warnings though, mostly related to the various feed scripts such as `wp-rss2.php`. I'm not sure if this is a bug in wp-cli or if some files have been left over from previous upgrades - it looks like the latter but I'll have to do some more digging to find out what the problem is.

**Comment by pwaring** [comment]
I've looked into this and verify-checksums returns a zero exit code when there are warnings (but no errors), which means the script will continue anyway. I'm waiting to see if there's an way to turn warnings into errors, as per this thread on the forums:

https://wordpress.org/support/topic/wp-cli-detecting-warnings-from-verify-checksums/

**Comment by pwaring** [comment]
I didn't get a response on the forums so I've just added `verify-checksums` as one of the steps and set all the commands to `--quiet`, so an email will only be sent (assuming run via cron) if there are errors or warnings.

I would like to add a `-Werrors` type argument to WP-CLI but I'm not sure if I have the time to do that.
